name: Generate Snake
 
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
 
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Generate snake
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: Jahongir1274
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=#FF3EA5&color_dots=#151021,#4a1942,#8b1e5c,#c92c6d,#ff3ea5
            dist/github-contribution-grid-snake-light.svg?color_snake=#FF3EA5&color_dots=#e8e4ec,#f2b8d4,#f480b3,#ff5aa0,#ff3ea5
 
      - name: Push snake svg
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
